import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  // --- HEADER: LENS & LEDS ---
  headerWrapper: {
    marginTop: 20,
    marginBottom: 40,
    width: '100%',
    paddingHorizontal: 20,
    zIndex: 10,
  },
  topInfoRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    paddingHorizontal: 10,
  },
  versionText: {
    color: 'rgba(255,255,255,0.6)',
    fontSize: 12,
    fontWeight: 'bold',
    letterSpacing: 1,
  },
  speechToggle: {
    padding: 6,
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  headerTrack: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#20252D', // Dark blue-ish grey
    width: '100%',
    height: 50,
    borderRadius: 25,
    borderWidth: 3,
    borderColor: '#111',
    paddingHorizontal: 15,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
  },
  leftLedContainer: {
    flex: 1,
    alignItems: 'flex-start',
    paddingLeft: 10,
  },
  rightLedsContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 8,
    paddingRight: 10,
  },
  mainLensContainer: {
    position: 'absolute',
    alignSelf: 'center',
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: '#DEDEDE', // Silver metallic ring base
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 3,
    borderColor: '#444',
    elevation: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.6,
    shadowRadius: 5,
    zIndex: 20,
  },
  mainLensInnerRing: {
    width: 76,
    height: 76,
    borderRadius: 38,
    backgroundColor: '#F5F5F5',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 2,
    borderColor: '#999',
  },
  mainLensGlass: {
    width: 60,
    height: 60,
    borderRadius: 30,
    borderWidth: 2,
    borderColor: '#000',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  lensReflection: {
    position: 'absolute',
    top: 5,
    left: 10,
    width: 25,
    height: 12,
    backgroundColor: 'rgba(255,255,255,0.7)',
    borderRadius: 10,
    transform: [{ rotate: '-45deg' }],
  },
  glassHighlight: {
    position: 'absolute',
    top: 2,
    right: 10,
    width: 10,
    height: 10,
    backgroundColor: 'rgba(255,255,255,0.8)',
    borderRadius: 5,
  },
  led: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1.5,
    borderColor: '#000',
  },
  ledRed: { backgroundColor: '#FF0000', shadowColor: '#FF0000', shadowOpacity: 0.8, shadowRadius: 5, elevation: 5 },
  ledYellow: { backgroundColor: '#FFCC00', shadowColor: '#FFCC00', shadowOpacity: 0.8, shadowRadius: 5, elevation: 5 },
  ledGreen: { backgroundColor: '#32CD32', shadowColor: '#32CD32', shadowOpacity: 0.8, shadowRadius: 5, elevation: 5 },
  ledBlueIdle: { backgroundColor: '#00FFFF', shadowColor: '#00FFFF', shadowOpacity: 0.8, shadowRadius: 10, elevation: 10 }
});
